#! /usr/bin/env bash

### Legal
#
# Author:  Thomas Debesse <dev@illwieckz.net>
# License: ISC
# 

set -u
set -e
set -o pipefail

drt_program_dir="$(dirname "$(realpath "${0}")")"

. "${drt_program_dir}/drt-common"

drt_program_zip="${drt_program_dir}/drt-zip"
. "${drt_program_zip}" "${@}" 'dummy'

temp_dir="$(mktemp -d "${TMPDIR}/drt-zipbrute-XXXXXXXX")"

temp_zip_dir="$(mktemp -d "${temp_dir}/drt-zipbrute-XXXXXXXX.zip.d")"
temp_zip_file="$(mktemp -u "${temp_dir}/drt-zipbrute-XXXXXXXX.zip")"

echo "temp_zip_dir: ${temp_zip_dir}"
echo "temp_zip_file: ${temp_zip_file}"

(
	touch_option='--no-touch'
	if "${touch_enable}"
	then
		touch_option='--touch'
		if "${epoch_enable}"
		then
			touch_option='--touch-epoch'
		fi
	fi

	chmod_option='--no-chmod'
	if "${chmod_enable}"
	then
		chmod_option='--chmod'
	fi

	directory_option='--directories'
	if ! "${directories_enable}"
	then
		directory_option='--no-directories'
	fi

	cd "${temp_zip_dir}"

	7za x "${zip_file}"

	if "${touch_enable}"
	then
		if [ "${epoch_enable}" ]
		then
			touch --date='@0' '.'
		fi

		touch --reference "${zip_file}" .
	fi

	"${drt_program_zip}" "${touch_option}" "${chmod_option}" "${directory_option}" "-${compression_level}" "${temp_zip_file}" '.'
)

touch --reference="${zip_file}" "${temp_zip_file}"
mv "${temp_zip_file}" "${zip_file}"
rm -R "${temp_zip_dir}"

rmdir "${temp_dir}"
