#! /bin/sh

### Legal
#
# Author:  Thomas Debesse <dev@illwieckz.net>
# License: ISC
# 

if [ "${1}" = '-q' ]
then
	exec 1>/dev/null
	exec 2>/dev/null
	shift
fi

file_name="${1}"

[ -z "${file_name}" ] && exit
[ ! -f "${file_name}" ] && exit

if [ -z "${TMPDIR}" ]
then
	TMPDIR='/tmp'
fi

temp_dir="$(mktemp -d "${TMPDIR}/drt-pngrute-XXXXXXXX")"

temp_file="$(mktemp "${temp_dir}/flac-XXXXXXXX.flac")"

flac_file="$(echo "${file_name}" | sed -e 's/\.[^.]*$/.flac/')"

ffmpeg -loglevel warning -y -i "${file_name}" "${temp_file}"
touch -r "${file_name}" "${temp_file}"

drt-flacbrute "${temp_file}"

cp "${temp_file}" "${flac_file}"

if [ -f "${temp_file}" ]
then
	touch -r "${temp_file}" "${flac_file}"
	rm "${file_name}"
fi

rm "${temp_file}"
rmdir "${temp_dir}"

#EOF
