#! /bin/sh

### Legal
#
# Author:  Thomas Debesse <dev@illwieckz.net>
# License: ISC
#

if [ -z "${1}" ]
then
	tree_dir='.'
else
	tree_dir="${1}"
	shift
fi

cd "${tree_dir}"

echo "make orphaned expired"
git reflog expire --expire=now --all

echo "garbage collect, prune"
git gc --prune=now --aggressive
