#! /bin/sh

### Legal
#
# Author:  Thomas Debesse <dev@illwieckz.net>
# License: ISC
# 

if [ "${1}" = '-7' ]
then
#	opt='-t7z -m0=lzma -mx=9 -mfb=64 -md=32m -ms=on'
	opt='-t7z -mx=9 -ms=on'
	shift
else
	opt='-tzip -mx=9'
fi

if [ "x${1}" = 'x' ]
then
	echo "missing file"
	exit
elif [ "$(echo "${1}" | cut -c1)" = '/' ]
then
	file="${1}"
else
	file="$(pwd)/${1}"
fi

if [ -z "${TMPDIR}" ]
then
	TMPDIR='/tmp'
fi

temp_dir="$(mktemp -d "${TMPDIR}/drt-zipbrute-XXXXXXXX")"

tmpzipdir="$(mktemp -d "${temp_dir}/drt-zipbrute-XXXXXXXX.zip.d")"
tmpzipfile="$(mktemp -u "${temp_dir}/drt-zipbrute-XXXXXXXX.zip")"

echo "tmpzipdir: ${tmpzipdir}"
echo "tmpzipfile: ${tmpzipfile}"

(cd "${tmpzipdir}"; 7za x "${file}")
(cd "${tmpzipdir}"; 7za a ${opt} "${tmpzipfile}" '.')
touch --reference="${file}" "${tmpzipfile}"
mv "${tmpzipfile}" "${file}"
rm -R "${tmpzipdir}"

rmdir "${temp_dir}"

#EOF
