#! /bin/sh

### Legal
#
# Author:  Thomas Debesse <dev@illwieckz.net>
# License: ISC
# 

if [ "${1}" = '-q' ]
then
	exec 1>/dev/null
	exec 2>/dev/null
	shift
fi

file_name="${1}"

[ -z "${file_name}" ] && exit
[ ! -f "${file_name}" ] && exit

if [ -z "${TMPDIR}" ]
then
	TMPDIR='/tmp'
fi

temp_dir="$(mktemp -d "${TMPDIR}/drt-mapdenum-XXXXXXXX")"

temp_file="$(mktemp -u "${temp_dir}/drt-mapdenum-XXXXXXXX.map")"
esquirel map -im "${file_name}" -dn -om "${temp_file}"
if [ -e "${temp_file}" ]
then
	touch --reference="${file_name}" "${temp_file}"
	mv "${temp_file}" "${file_name}"
fi

rmdir "${temp_dir}"

#EOF
