#! /usr/bin/env bash

### Legal
#
# Author:  Thomas Debesse <dev@illwieckz.net>
# License: ISC
# 

set -u -e -o pipefail

tag_name='.'

# enable_zopfli='true'
# if [ "${1}" = '-n' ]
# then
# 	enable_zopfli='false'
# 	shift
# fi

if [ "${1}" = '-q' ]
then
	exec 1>/dev/null
	exec 2>/dev/null
	shift
fi

do_pngcrush='true'
do_advpng='true'
do_advpng_zopfli='false'
do_oxipng='false'
do_oxipng_zopfli='true'
do_pngwolf='false'
do_pngwolf_zopfli='true'

case "${1}" in
	'-a'|'-all')
		do_pngcrush='true'
		do_advpng='true'
		do_advpng_zopfli='false'
		do_oxipng='false'
		do_oxipng_zopfli='true'
		do_pngwolf='false'
		do_pngwolf_zopfli='true'
		shift
		;;
	'--pngcrush')
		do_pngcrush='true'
		do_advpng='false'
		do_advpng_zopfli='false'
		do_oxipng='false'
		do_oxipng_zopfli='false'
		do_pngwolf='false'
		do_pngwolf_zopfli='false'
		shift
		;;
	'--advpng')
		do_pngcrush='false'
		do_oxipng='false'
		do_advpng='true'
		do_advpng_zopfli='false'
		do_oxipng_zopfli='false'
		do_pngwolf='false'
		do_pngwolf_zopfli='false'
		shift
		;;
	'--advpng')
		do_pngcrush='false'
		do_oxipng='false'
		do_advpng='false'
		do_advpng_zopfli='true'
		do_oxipng_zopfli='false'
		do_pngwolf='false'
		do_pngwolf_zopfli='false'
		shift
		;;
	'--oxipng')
		do_pngcrush='false'
		do_advpng='false'
		do_advpng_zopfli='false'
		do_oxipng='true'
		do_oxipng_zopfli='false'
		do_pngwolf='false'
		do_pngwolf_zopfli='false'
		shift
		;;
	'--oxipng-zopfli')
		do_pngcrush='false'
		do_advpng='false'
		do_advpng_zopfli='false'
		do_oxipng='false'
		do_oxipng_zopfli='true'
		do_pngwolf='false'
		do_pngwolf_zopfli='false'
		shift
		;;
	'--pngwolf')
		do_pngcrush='false'
		do_advpng='false'
		do_advpng_zopfli='false'
		do_oxipng='false'
		do_oxipng_zopfli='false'
		do_pngwolf='true'
		do_pngwolf_zopfli='false'
		shift
		;;
	'--pngwolf-zopfli')
		do_pngcrush='false'
		do_advpng='false'
		do_advpng_zopfli='false'
		do_oxipng='false'
		do_oxipng_zopfli='false'
		do_pngwolf='false'
		do_pngwolf_zopfli='true'
		shift
		;;
	*)
		;;
esac

if [ "${1}" = '-t' ]
then
	shift
	if ! [ -z "${1}" ]
	then
		tag_name="${1}"
		shift
	else 
		printf 'ERROR: -t needs tag name\n' >&2
		exit 1
	fi
fi

file_name="${1}"

[ -z "${file_name}" ] && exit
[ ! -f "${file_name}" ] && exit

isSmaller () {
	size1="$(stat -c%s "${1}")"
	size2="$(stat -c%s "${2}")"

	[ "${size1}" -lt "${size2}" ]
}

useOrDeleteIfSmaller () {
	if isSmaller "${1}" "${2}"
	then
		touch -r "${2}" "${1}"
		cp -a --reflink=auto "${1}" "${2}"
	fi

	rm "${1}"

	sync
}

getSum () {
	sha512sum "${1}" | cut -f1 -d' '
}

getRgbaSum () {
	local rgba_file="$(mktemp "${temp_dir}/rgba-XXXXXXXX.rgba")"
	convert "${1}" "${rgba_file}"
	getSum "${rgba_file}"
	rm "${rgba_file}"
}

checkFile () {
	case "$(getRgbaSum "${1}")" in
		"${file_sum}");;
		*)
			echo "ERROR: invalid RGBA stream after conversion in ${1}" >&2
			false
		;;
	esac
}

preferFile () {
	if [ -f "${1}" ]
	then
		# It can happen that pngcrush fails but doesn't return
		# an error code and write an empty file, so we should
		# not use that empty file as if it was the optimized one.
		if [ "$(du -b "${1}" | cut -f1 -d$'\t')" = '0' ]
		then
			rm "${1}"
		# It can happen that pngcrush writes an invalid file,
		# we should not use it.
		elif checkFile "${1}"
		then
			useOrDeleteIfSmaller "${1}" "${2}"
		fi
	fi
}

TMPDIR="${TMPDIR-/tmp}"

temp_dir="$(mktemp -d "${TMPDIR}/drt-pngrute-XXXXXXXX")"

cache_basepath="pngbrute";
cache_basedir="$(realpath "${XDG_CACHE_HOME:-${HOME}/.cache}/${cache_basepath}")";
cache_dir="$(realpath "${XDG_CACHE_HOME:-${HOME}/.cache}/${cache_basepath}/${tag_name}")";

mkdir -p "${cache_dir}"
echo "= PNGBRUTE ========= ${file_name}"

mkdir -p "${cache_dir}"

file_sum="$(getRgbaSum "${file_name}")"

temp_file="$(mktemp "${temp_dir}/png-XXXXXXXX.png")"
cp -a --reflink=auto "${file_name}" "${temp_file}"

oxipng --opt 0 --interlace 0 --strip all "${temp_file}"
checkFile "${temp_file}"

cache_file="$(find "${cache_basedir}" -type f -name "${file_sum}" | tail -n1)"
new_cache_file="${cache_dir}/${file_sum}"

echo "file sum: ${file_sum}"
echo "cache file: ${cache_file}"

if [ -f "${cache_file}" ]
then
	if ! checkFile "${cache_file}"
	then
		rm "${cache_file}"
	fi

	echo "already bruteforced"

	if [ "${file_name}" -ot "${cache_file}" ]
	then
		echo "older than previous reference"
		touch -r "${file_name}" "${cache_file}"
	fi

	cp -a --reflink=auto "${cache_file}" "${file_name}"
fi

runCrusher () {
	local do="${1}"; shift
	local task="${1}"; shift

	if "${do}"
	then
		echo "== processing ${file_name} with ${task} =="

		crush_file="$(mktemp "${temp_dir}/${task}-XXXXXXXX.png")"

		local advpng_iter=1000
		local advpng_zopfli_iter=1000
		local pngwolf_stagnate=1000
		local pngwolf_zopfli_iter=5000

		case "${task}" in
			'pngcrush')
				# It can happen that pngcrush fails but doesn't return
				# an error code and write an empty file or even return
				# an invalid file.
				pngcrush "${temp_file}" "${crush_file}" || true
			;;
			'advpng')
				# It can happens sometime that advpng fails.
				# > Error reading the signature on file.png [at void throw_png_error():pngex.h:37]
				advpng -z -3 -i "${advpng_iter}" "${crush_file}" || true
			;;
			'advpng-zopfli')
				advpng -z -4 -i "${advpng_zopfli_iter}" "${crush_file}" || true
			;;
			'oxipng')
				# Do not use `oxipng --alpha` because the alpha channel
				# may still be used as a standalone component.
				oxipng --opt 6 --strip all --out "${crush_file}" "${temp_file}"
			;;
			'oxipng-zopfli')
				oxipng --opt 6 --zopfli --strip all --out "${crush_file}" "${temp_file}"
			;;
			'pngwolf')
				pngwolf --max-stagnate-time="${pngwolf_stagnate}" \
					--in="${temp_file}" \
					--out="${crush_file}"
			;;
			'pngwolf-zopfli')
				pngwolf --max-stagnate-time="${pngwolf_stagnate}" \
					--out-deflate="zopfli,iter=${pngwolf_zopfli_iter},maxsplit=0,verbose=1" \
					--in="${temp_file}" \
					--out="${crush_file}"
			;;
		esac
	fi
}

if [ ! -f "${cache_file}" ]
then
	convert "${temp_file}" +set comment -define png:exclude-chunks=date "${temp_file}"
	checkFile "${temp_file}"

	crush_files=()

	runCrusher "${do_pngcrush}" 'pngcrush'
	runCrusher "${do_advpng}" 'advpng'
	runCrusher "${do_advpng_zopfli}" 'advpng-zopfli'
	runCrusher "${do_oxipng}" 'oxipng'
	runCrusher "${do_oxipng_zopfli}" 'oxipng-zopfli'
	runCrusher "${do_pngwolf}" 'pngwolf'
	runCrusher "${do_pngwolf_zopfli}" 'pngwolf-zopfli'

	touch -r "${file_name}" "${temp_file}"

	preferFile "${temp_file}" "${file_name}"

	cp -a --reflink=auto "${file_name}" "${new_cache_file}"
fi

rm -f "${temp_file}"

rmdir "${temp_dir}"

#EOF
