#! /bin/sh

### Legal
#
# Author:  Thomas Debesse <dev@illwieckz.net>
# License: ISC
# 

if [ "${1}" = '-q' ]
then
	exec 1>/dev/null
	exec 2>/dev/null
	shift
fi

file_name="${1}"

if [ -z "${TMPDIR}" ]
then
	temp_dir="$(mktemp -d "/tmp/drt-flacbrute-XXXXXXXX}")"
else
	temp_dir="$(mktemp -d "${TMPDIR}/drt-flacbrute-XXXXXXXX")"
fi

[ -z "${file_name}" ] && exit
[ ! -f "${file_name}" ] && exit

temp_file="$(mktemp "${temp_dir}/drt-flacbrute-XXXXXXXX")"
temp_flac="${temp_file}.flac"

cp -a "${file_name}" "${temp_file}"

flac -8 "${temp_file}"

if [ -e "${temp_flac}" ]
then
	touch --reference="${file_name}" "${temp_flac}"
	mv "${temp_flac}" "${file_name}"
fi

rm "${temp_file}"
rmdir "${temp_dir}"

#EOF
