#! /usr/bin/env bash

### Legal
#
# Author:  Thomas Debesse <dev@illwieckz.net>
# License: ISC
# 

set -u -e -o pipefail

TMPDIR="${TMPDIR-/tmp}"
temp_dir="$(mktemp -d "${TMPDIR}/drt-pngrute-XXXXXXXX")"

while [ -n "${1:-}" ]
do
	file_name="${1}"; shift

	if [ ! -f "${file_name}" ]
	then
		printf 'Not a file: %s\n' "${file_name}" 2>&1
		continue
	fi

	rgba_file="$(mktemp "${temp_dir}/rgba-XXXXXXXX.rgba")"
	convert "${file_name}" "${rgba_file}"
	rgba_sum="$(sha512sum -b "${rgba_file}" | cut -f1 -d' ')"
	printf '%s %s\n' "${rgba_sum}" "${file_name}"
	rm "${rgba_file}"
done
