#! /usr/bin/env bash

set -u
set -e
set -o pipefail

_error () {
	local format="${1}"; shift

	printf "ERROR: ${format}\n" "${@}" >&2
	return 1
}

if command -v parallel >/dev/null
then
	if ! parallel --will-cite --bar --halt now,fail=1 "${@}"
	then
		_error 'failed to execute tasks'
	fi
elif command -v xargs >/dev/null
then
	if ! xargs "${@}"
	then
		_error 'failed to execute tasks'
	fi
else
	_error 'your system must provide parallel or xargs'
fi

#EOF
