#! /bin/sh

### Legal
#
# Author:  Thomas Debesse <dev@illwieckz.net>
# License: ISC
# 

_error () {
	printf 'ERROR: %s\n' "${1}" >&2
	exit 1
}

if ! [ -x "$(which git)" ]
then
	_error 'git not installed'
fi

if ! [ "$(git rev-parse --is-inside-work-tree 2>/dev/null)" = 'true' ]
then
	_error 'not within git repository'
fi

if ! [ "$(git status --short 2>/dev/null)" = '' ]
then
	_error 'repository has untracked or unstaged files, please commit changes first'
fi

if ! [ "$(git diff --shortstat 2>/dev/null | tail -n1)" = '' ]
then
	_error 'repository is dirty, please commit changes first'
fi

#EOF
