#!/bin/sh

### Legal
#
# Author:  Thomas Debesse <dev@illwieckz.net>
# License: ISC
# 

if [ "${1}" = '-q' ]
then
	exec 1>/dev/null
	exec 2>/dev/null
	shift
fi

dir_name="${1}"
shift
file_name="${@}"

[ -z "${file_name}" ] && exit
[ ! -f "${file_name}" ] && exit

getSum () {
	sha512sum "${1}" | cut -f1 -d' '
}

rgba_file="$(mktemp "${dir_name}/rgba-XXXXXXXX.rgba")"

convert "${file_name}" "${rgba_file}"
png_file="${dir_name}/$(getSum "${rgba_file}").png"
[ -f "${png_file}" ] || cp "${file_name}" "${png_file}"

rm "${rgba_file}"

#EOF
